name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Install dependencies
      run: |
        npm install
        npx react-native info

    - name: Log in to EAS
      run: eas login --token ${{ secrets.EXPO_TOKEN }}

    - name: Build and test
      run: eas build --platform android --profile your-build-profile

    - name: Run tests
      run: npm test
